# Generated by Django 5.1.7 on 2025-03-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers_app', '0010_alter_offerdetails_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
                ('delivery_time_in_days', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_time_in_days+', to='offers_app.offerdetails')),
                ('features', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features+', to='offers_app.offerdetails')),
                ('offer_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_type+', to='offers_app.offerdetails')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price+', to='offers_app.offerdetails')),
                ('revisions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisions+', to='offers_app.offerdetails')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title+', to='offers_app.offerdetails')),
            ],
        ),
    ]
