# Generated by Django 5.1.7 on 2025-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_in_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='features',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=255),
        ),
    ]
