# Generated by Django 5.1.7 on 2025-03-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0010_alter_offerdetails_features'),
        ('orders_app', '0002_remove_order_offer_order_offerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offerdetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_offerdetails', to='offers_app.offerdetails'),
        ),
    ]
