# Generated by Django 5.1.7 on 2025-03-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_alter_offer_options_alter_offer_image_offerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetails',
            name='delivery_time_in_days',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='price',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='revisions',
            field=models.CharField(default='10', max_length=255),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='title',
            field=models.CharField(default='detail titel', max_length=255),
        ),
    ]
