# Generated by Django 5.1.7 on 2025-03-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_offerdetails_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetails',
            name='delivery_time_in_days',
        ),
        migrations.RemoveField(
            model_name='offerdetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='offerdetails',
            name='revisions',
        ),
    ]
