# Generated by Django 5.1.7 on 2025-03-21 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_remove_offerdetails_delivery_time_in_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.CharField(default='000', max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.CharField(default='000', max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
