# Generated by Django 5.1.6 on 2025-03-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_rename_updated_at_offer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
