# Generated by Django 5.1.7 on 2025-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offer_created_at_alter_offer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
