# Generated by Django 5.1.7 on 2025-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0007_alter_offer_created_at_alter_offer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetails',
            name='delivery_time_in_days',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='revisions',
            field=models.IntegerField(default=0),
        ),
    ]
