# Generated by Django 5.1.7 on 2025-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0008_offerdetails_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='features',
            field=models.JSONField(),
        ),
    ]
