# Generated by Django 5.1.7 on 2025-03-28 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_alter_reviews_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('reviewer', 'business_user'), name='unique_review_per_user_pair'),
        ),
    ]
