# Generated by Django 5.1.7 on 2025-03-13 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=30)),
                ('last_name', models.CharField(default='last name', max_length=30)),
                ('file', models.FileField(default='default.jpg', upload_to='uploads/')),
                ('location', models.CharField(default='location', max_length=30)),
                ('tel', models.CharField(default='+49 123456789', max_length=30)),
                ('description', models.CharField(default='description', max_length=30)),
                ('working_hours', models.CharField(default='24h', max_length=30)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default='customer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
