# Generated by Django 5.1.7 on 2025-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.CharField(max_length=255)),
            ],
        ),
    ]
