# Generated by Django 5.1.6 on 2025-03-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='uploads/profiles/'),
        ),
    ]
