# Generated by Django 5.1.7 on 2025-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_alter_userprofile_created_at_alter_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
